// Auto-generated by update-contract-addresses.js
// Last updated: 2025-07-28T16:01:54.269Z

export const contractAddresses = {
  savingsGroup: "0x71b6977A253643378e0c5f05BA6DCF7295aBD4FA",
  microloanSystem: "0x01C22438586BDD5a8d8481F409f841F35B2281fA"
};
